# name: Docker Image CI

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:

#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
      
on:
  push
jobs:
  building:
    name: Checkouts
    runs-on: ubuntu-latest
    steps:
      -
        name: Pull the repository
        uses: actions/checkout@v2
      -
        run: ls
      -
        run: docker build -t idle_image .
      -
        run: docker images
      -
        run: docker run -i idle_image
