name: Docker Image CI


# on:
#   push
# jobs:
#   building:
#     name: Checkouts
    
#     steps:
#       -
#         name: Pull the repository
#         uses: actions/checkout@v2
#       -
#         run: ls
#       -
#         run: docker build -t idle_image .
#       -
#         run: docker images
#       -
#         run: docker run --rm -t -v /datas:/data idle_image
#       -
#         run: date > dates.log
        
#         name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Pull the repository
    uses: actions/checkout@v2
    run: ls
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: ls
      
      run: docker build -t idle_image2
      -
      run: docker images
      -
      run: docker run  -it --name test3 idle_image2
      -
